// The SBOM: the SPDX document the BUILD attested to the image (GitHub artifact attestation, else
// cosign), verified against the build reusable's signer; falls back to generating one with Syft.
import { writeFileSync } from "node:fs";
import type { Ctx } from "./types.ts";

export default async function run({ core, exec }: Ctx): Promise<void> {
  const ref = process.env.REF || "";
  const owner = process.env.GITHUB_REPOSITORY_OWNER || "";
  let origin = "";
  if ((process.env.SBOM_SOURCE || "build") === "build") {
    // Signed by the BUILD reusable's identity (this org's docker-multiarch-cicd.yaml), not the caller's repo.
    const gh = await exec.getExecOutput("gh", ["attestation", "verify", `oci://${ref}`, "--owner", owner,
      "--signer-repo", "ohanalabs-ai/github-platform", "--predicate-type", "https://spdx.dev/Document/v2.3", "--format", "json"],
      { silent: true, ignoreReturnCode: true });
    if (gh.exitCode === 0) {
      try {
        const predicate = (JSON.parse(gh.stdout) as Array<{ verificationResult: { statement: { predicate: unknown } } }>)[0]
          ?.verificationResult?.statement?.predicate;
        if (predicate) { writeFileSync("sbom.spdx.json", JSON.stringify(predicate)); origin = "build attestation (GitHub, verified)"; }
      } catch { /* not an attestation payload — fall through */ }
    }
    if (!origin) {
      const co = await exec.getExecOutput("cosign", ["download", "attestation", "--predicate-type", "spdxjson", ref], { silent: true, ignoreReturnCode: true })
        .catch(() => ({ exitCode: 1, stdout: "", stderr: "" }));
      const line = co.exitCode === 0 ? co.stdout.split("\n").find((l) => l.trim()) : undefined;
      if (line) {
        try {
          const payload = JSON.parse(Buffer.from((JSON.parse(line) as { payload: string }).payload, "base64").toString("utf8")) as { predicate?: unknown };
          if (payload.predicate) { writeFileSync("sbom.spdx.json", JSON.stringify(payload.predicate)); origin = "build attestation (cosign)"; }
        } catch { /* fall through */ }
      }
    }
    if (!origin) core.notice(`no SBOM attestation found on ${ref} — generating one with Syft`);
  }
  if (!origin) {
    await exec.exec("syft", [`registry:${ref}`, "-o", "spdx-json=sbom.spdx.json", "-q"]);
    origin = "generated by Syft in this job";
  }
  core.setOutput("origin", origin);
}
